param(
  [Parameter(Mandatory = $true)]
  [string]$Name,
  [Parameter(Mandatory = $true)]
  [string]$Domain,
  [Parameter(Mandatory = $true)]
  [string]$Identity,
  [string]$ScopesComma = "read_products"
)

# ──────────────────────────────────────────────────────────────────────────────
# new-app.ps1 — onboarding generator for a new Shopify app on this codebase.
#
# Usage:
#   ./scripts/new-app.ps1 -Name newclient -Domain newclient.cpg-labs.io -Identity newclient
#
# What it does (pure file writes, NO cloud mutations):
#   1. Stubs `shopify.app.<name>.toml` mirroring `shopify.app.storytelling.toml`.
#   2. Appends a `module "<name>"` block to `infra/terraform/apps.tf`
#      (creates the file if it doesn't exist yet).
#   3. Appends an entry to `scripts/apps.psd1`.
#
# Prints the three manual follow-ups that remain:
#   a. Create the Shopify app in Partner Dashboard, paste client_id + client_secret
#      into `infra/terraform/terraform.tfvars`.
#   b. Add the hostname to DNS (CNAME → ALB).
#   c. Add the hostname to the ACM cert SAN list (or use wildcard `*.cpg-labs.io`).
# ──────────────────────────────────────────────────────────────────────────────

$ErrorActionPreference = "Stop"

# Validate slug — lowercase letters, digits, hyphen. This becomes a Terraform
# module label, a Shopify TOML filename, and an apps.psd1 key, so restrict
# characters accordingly.
if ($Name -notmatch '^[a-z][a-z0-9-]*$') {
  throw ("Invalid -Name '{0}'. Must be lowercase alphanumeric + hyphen, starting with a letter." -f $Name)
}

$repoRoot     = Resolve-Path (Join-Path $PSScriptRoot "..")
$tomlTemplate = Join-Path $repoRoot "shopify.app.storytelling.toml"
$tomlTarget   = Join-Path $repoRoot ("shopify.app.{0}.toml" -f $Name)
$appsTf       = Join-Path $repoRoot "infra/terraform/apps.tf"
$manifest     = Join-Path $PSScriptRoot "apps.psd1"

# ── 1. shopify.app.<name>.toml ────────────────────────────────────────────────

if (Test-Path $tomlTarget) {
  Write-Warning ("{0} already exists — skipping TOML generation." -f $tomlTarget)
} else {
  if (Test-Path $tomlTemplate) {
    $tomlBody = Get-Content -Raw -Path $tomlTemplate
    # Best-effort substitutions mirroring storytelling's shape.
    $tomlBody = $tomlBody -replace 'https://storytelling\.cpg-labs\.io', ("https://{0}" -f $Domain)
    $tomlBody = $tomlBody -replace 'name = "Story-telling"', ('name = "{0}"' -f $Name)
    $tomlBody = $tomlBody -replace 'scopes = "[^"]*"', ('scopes = "{0}"' -f $ScopesComma)
    # Ensure the client_id is a fresh placeholder so reviewers don't paste the
    # storytelling app's id by accident.
    $tomlBody = $tomlBody -replace 'client_id = "[^"]*"', 'client_id = "<PLACEHOLDER>"'
    Set-Content -Path $tomlTarget -Value $tomlBody -Encoding UTF8
  } else {
    # Fallback template if storytelling file isn't available.
    $tomlBody = @"
# $Name — generated by scripts/new-app.ps1 on $(Get-Date -Format "yyyy-MM-dd")
# Register a new app in Shopify Partner Dashboard and paste the client_id here.

client_id = "<PLACEHOLDER>"
name = "$Name"
application_url = "https://$Domain"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = "$ScopesComma"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://$Domain/api/auth" ]
"@
    Set-Content -Path $tomlTarget -Value $tomlBody -Encoding UTF8
  }
  Write-Host ("Wrote {0}" -f $tomlTarget)
}

# ── 2. infra/terraform/apps.tf ────────────────────────────────────────────────

$moduleBlock = @"

module "$Name" {
  source             = "./modules/shopify-app"
  app_name           = "$Name"
  domain             = "$Domain"
  app_identity       = "$Identity"
  shopify_api_key    = var.shopify_api_key_$Name
  shopify_api_secret = var.shopify_api_secret_$Name
  shopify_scopes     = "$ScopesComma"
  image_tag          = var.image_tag_$Name
  # extra_env        = [ /* app-specific env vars */ ]
}
"@

if (-not (Test-Path $appsTf)) {
  $header = @"
# infra/terraform/apps.tf — one `module "…"` block per Shopify app.
# Generated/extended by scripts/new-app.ps1.
"@
  Set-Content -Path $appsTf -Value $header -Encoding UTF8
  Write-Host ("Created {0}" -f $appsTf)
}

$existing = Get-Content -Raw -Path $appsTf
if ($existing -match ('module\s+"' + [regex]::Escape($Name) + '"')) {
  Write-Warning ("apps.tf already contains module ""{0}"" — skipping Terraform append." -f $Name)
} else {
  Add-Content -Path $appsTf -Value $moduleBlock -Encoding UTF8
  Write-Host ("Appended module ""{0}"" to {1}" -f $Name, $appsTf)
}

# ── 3. scripts/apps.psd1 ──────────────────────────────────────────────────────

$manifestContent = Get-Content -Raw -Path $manifest
if ($manifestContent -match ("'" + [regex]::Escape($Name) + "'\s*=")) {
  Write-Warning ("apps.psd1 already contains '{0}' — skipping manifest append." -f $Name)
} else {
  $tagPrefix    = "cpg-labs-$Name"
  $service      = "cpg-labs-$Name-service"
  $taskFamily   = "cpg-labs-$Name-task"
  $healthUrl    = "https://$Domain/health"
  $imageTagVar  = "image_tag_$($Name -replace '-','_')"

  # Insert before the closing `}` of the manifest hashtable. The manifest is a
  # single top-level hashtable, so we anchor on the LAST `}` in the file.
  $lineToAdd = "  '{0}' = @{{ service = '{1}'; task_family = '{2}'; health_url = '{3}'; tag_prefix = '{4}'; image_tag_var = '{5}' }}" -f $Name, $service, $taskFamily, $healthUrl, $tagPrefix, $imageTagVar
  $lines = Get-Content -Path $manifest
  # Find last line that is just a closing brace (ignoring whitespace).
  $closeIdx = -1
  for ($i = $lines.Count - 1; $i -ge 0; $i--) {
    if ($lines[$i].Trim() -eq '}') { $closeIdx = $i; break }
  }
  if ($closeIdx -lt 0) { throw "Could not locate closing '}' in apps.psd1 — manifest shape unexpected." }
  $newLines = @()
  $newLines += $lines[0..($closeIdx - 1)]
  $newLines += $lineToAdd
  $newLines += $lines[$closeIdx..($lines.Count - 1)]
  Set-Content -Path $manifest -Value $newLines -Encoding UTF8
  Write-Host ("Appended '{0}' entry to {1}" -f $Name, $manifest)
}

# ── follow-up instructions ────────────────────────────────────────────────────

Write-Host ""
Write-Host "Three manual follow-ups remain:" -ForegroundColor Cyan
Write-Host ("  1. Partner Dashboard: create the '{0}' app, copy client_id + client_secret" -f $Name)
Write-Host ("     into infra/terraform/terraform.tfvars as")
Write-Host ("       shopify_api_key_{0}    = ""<client_id>""" -f $Name)
Write-Host ("       shopify_api_secret_{0} = ""<client_secret>""" -f $Name)
Write-Host ("  2. DNS: add a CNAME/ALIAS for {0} pointing at the ALB." -f $Domain)
Write-Host ("  3. ACM: add {0} to the certificate SAN list, or rely on the" -f $Domain)
Write-Host ("     wildcard *.cpg-labs.io cert if the hostname is under that domain.")
