# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "68903b9706c70055a4410acce22a3e9a"
name = "Omnify"
application_url = "https://omnify.cpg-labs.io"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "customers/create", "customers/update", "customers/delete" ]
  uri = "/webhooks/customers"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/updated", "orders/delete" ]
  uri = "/webhooks/orders"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_publications,read_shipping,write_shipping,write_orders,write_merchant_managed_fulfillment_orders,read_content,write_content,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://omnify.cpg-labs.io/api/auth" ]
