"""scripts/deliver.py — Phase 9 final drop-folder writer.

Creates the canonical ship-ready Meta package at state/<concept>/output/ and
transitions state.state -> DELIVERED.

Layout produced:
    state/<concept>/output/
    ├── README.md                    # Generated from template, addressed to traffic specialist
    ├── base/
    │   ├── creative.mp4
    │   ├── thumbnail.jpg
    │   ├── captions.srt
    │   └── copy.txt
    ├── variant-a/
    │   ├── creative.mp4
    │   ├── thumbnail.jpg
    │   ├── captions.srt
    │   └── copy.txt
    └── variant-b/
        ├── creative.mp4
        ├── thumbnail.jpg
        ├── captions.srt
        └── copy.txt

All four files per variant must already exist (the assembler writes them). This
script just confirms they're present, writes the top-level README, and bumps
state.

CLI:
    python deliver.py --concept-id <id>
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from state import (  # noqa: E402
    read_state,
    update_state,
    transition,
    append_event,
    utcnow_iso,
    concept_dir,
)


REQUIRED_FILES = ["creative.mp4", "thumbnail.jpg", "captions.srt", "copy.txt"]


def check_variant_files(output_dir: Path, variant: str) -> tuple[bool, list[str]]:
    """Returns (all_present, missing_files)."""
    vdir = output_dir / variant
    if not vdir.exists():
        return False, REQUIRED_FILES.copy()
    missing = [f for f in REQUIRED_FILES if not (vdir / f).exists()]
    return (len(missing) == 0), missing


def render_readme(state: dict, variants_present: list[str]) -> str:
    product = state.get("product", {})
    title = product.get("title", "?")
    gid = product.get("gid", "?")
    handle = product.get("handle", "?")
    price = product.get("price_brl", "?")
    concept_id = state.get("concept_id", "?")
    concept_label = state.get("concept_label", concept_id)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Pull copy per variant
    base_copy = state.get("ad_copy", {})
    alt_copy = state.get("ad_copy_variant_b", {})

    def copy_block(label: str, copy: dict) -> str:
        if not copy:
            return f"### {label}\n(no copy recorded)\n"
        lines = [f"### {label}"]
        for k in ("primary_text", "headline", "link_description", "cta_button"):
            v = copy.get(k, "")
            if v:
                lines.append(f"- **{k}:** {v}")
        return "\n".join(lines) + "\n"

    # Render history
    spent = state.get("budget", {}).get("spent_usd", 0)
    shots = state.get("shots", [])
    n_shots = len(shots)
    total_clip_s = sum(sh.get("duration_s", 6) for sh in shots)
    models = sorted({sh.get("model_label") for sh in shots if sh.get("model_label")})
    audio_source = "Seedance 2.0 native" if any(
        "seedance" in (sh.get("motion_model_slug", "") + sh.get("model_slug", "")).lower()
        for sh in shots
    ) else "varied"

    variants_table = "\n".join(
        f"| {v} | output/{v}/creative.mp4 |"
        for v in variants_present
    )

    return f"""# {concept_label} — Meta package
Generated: {today}
Product: {title} (R${price})
Shopify GID: {gid}
Concept: {concept_id}

## Files
{len(variants_present)} variant(s) ready for Meta Ads Manager upload.

| Variant | Path |
|---|---|
{variants_table}

Each variant folder contains:
- `creative.mp4` — the ad asset, 9:16, ~18-20s
- `thumbnail.jpg` — cover frame
- `captions.srt` — sidecar captions for accessibility
- `copy.txt` — primary_text + headline + link_description + CTA, ready to paste

## Recommended A/B split
- 33% base
- 33% variant-a (reverse-teaser arc — opens with the evening payoff)
- 33% variant-b (alternative copy angle)

## Copy per variant

{copy_block("base", base_copy)}
{copy_block("variant-b (alt copy)", alt_copy)}

> variant-a uses the same copy as base.

## Render history
- Shots: {n_shots} @ ~{total_clip_s:.1f}s total source duration, ~$ {spent:.2f} USD spent (or ~credits on Magnific Premium+)
- Models used: {', '.join(models) if models else 'n/a'}
- Audio: {audio_source}

## Notes
- Aspect: 9:16 vertical
- Length: ~18-20s
- Brand: GE Beauty
- Tagline: no seu tempo, do seu jeito.
- Faceless + hair-out (no humans, no hair, no hands)

Generated by /video-director.
"""


def cmd_run(args):
    state = read_state(args.concept_id)
    cdir = concept_dir(args.concept_id)
    output_dir = cdir / "output"

    if not output_dir.exists():
        raise SystemExit(f"no output/ directory at {output_dir} — run assemble.py first")

    # Check each variant
    candidates = ("base", "variant-a", "variant-b")
    variants_present = []
    missing_report = {}
    for v in candidates:
        ok, missing = check_variant_files(output_dir, v)
        if ok:
            variants_present.append(v)
        elif missing:
            missing_report[v] = missing

    if "base" not in variants_present:
        print("[deliver] FAIL: base variant missing required files")
        for f in missing_report.get("base", []):
            print(f"  missing: output/base/{f}")
        sys.exit(2)

    if missing_report:
        print("[deliver] WARN: some variants incomplete:")
        for v, files in missing_report.items():
            if v not in variants_present:
                print(f"  {v}: missing {', '.join(files)}")

    print(f"[deliver] variants present: {', '.join(variants_present)}")

    # Write the top-level README
    readme = output_dir / "README.md"
    readme_text = render_readme(state, variants_present)
    readme.write_text(readme_text, encoding="utf-8")
    print(f"[deliver] wrote {readme}")

    # State transition
    def m(s):
        s.setdefault("delivery", {})
        s["delivery"]["delivered_at"] = utcnow_iso()
        s["delivery"]["packages"] = variants_present
        s["delivery"]["output_dir"] = str(output_dir.relative_to(cdir).as_posix())
        if s.get("state") != "DELIVERED":
            transition(s, "DELIVERED", actor="deliver", packages=variants_present)
        else:
            append_event(s, actor="deliver", event="redelivered", packages=variants_present)
        return s
    update_state(args.concept_id, m)

    print(f"[deliver] DONE -> state.state = DELIVERED")
    print(f"[deliver] drop folder: {output_dir}")


def cmd_status(args):
    state = read_state(args.concept_id)
    cdir = concept_dir(args.concept_id)
    output_dir = cdir / "output"
    print(f"concept: {args.concept_id}")
    print(f"state:   {state.get('state')}")
    print(f"output:  {output_dir}")
    print()
    for v in ("base", "variant-a", "variant-b"):
        ok, missing = check_variant_files(output_dir, v)
        if ok:
            print(f"  {v}: READY")
        elif missing == REQUIRED_FILES:
            print(f"  {v}: not assembled yet")
        else:
            print(f"  {v}: partial (missing: {', '.join(missing)})")
    print()
    if delivery := state.get("delivery"):
        print(f"delivered_at: {delivery.get('delivered_at')}")
        print(f"packages:     {delivery.get('packages')}")


def main():
    parser = argparse.ArgumentParser(description="Deliver the final Meta package for /video-director.")
    sub = parser.add_subparsers(dest="cmd", required=True)

    rp = sub.add_parser("run", help="Write README + transition state to DELIVERED")
    rp.add_argument("--concept-id", required=True)
    rp.set_defaults(func=cmd_run)

    st = sub.add_parser("status", help="Print delivery readiness")
    st.add_argument("--concept-id", required=True)
    st.set_defaults(func=cmd_status)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
