"""Build the static b2b.gebeauty.com.br site content from the two decks.

Inputs:
  - inputs/mockups/gebeauty-b2b-portfolio-v6.html   (commercial deck)
  - inputs/mockups/gebeauty-portfolio-neutral-v1.html (neutral/partner deck,
    regenerated by _b2b_make_neutral.py -- run that first if v6 changed)

Transform: rewrite the 7 @font-face `src:url('https://www.gebeauty.com.br/
cdn/shop/t/34/...')` references to inline base64 `data:` URIs, sourced from
the local font cache (see FONT_DIR), so the deployed pages have zero runtime
dependency on the Shopify theme CDN (handoff §3 -- images were already
inlined as data:image/webp; this closes the last external-asset gap).

Output: gebeauty/b2b-site/{comercial,parceiros}/index.html

Usage: C:/Python314/python.exe gebeauty/scripts/_b2b_build_site.py
"""
import base64
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1].parent
MOCK = ROOT / "inputs" / "mockups"
FONT_DIR = ROOT / "gebeauty" / "b2b-site" / "_fonts-src"
SITE = ROOT / "gebeauty" / "b2b-site"

FONT_MIME = {".woff2": "font/woff2", ".ttf": "font/ttf"}

# Matches src:url('https://www.gebeauty.com.br/cdn/shop/t/34/assets/<file>?v=...') format('...')
FONT_URL_RE = re.compile(
    r"url\('https://www\.gebeauty\.com\.br/cdn/shop/t/34/assets/([^'\?]+)\?[^']*'\)"
)


def inline_fonts(html: str, label: str) -> str:
    seen = set()

    def repl(m):
        fname = m.group(1)
        seen.add(fname)
        fpath = FONT_DIR / fname
        if not fpath.exists():
            raise FileNotFoundError(f"{label}: missing font source {fpath}")
        mime = FONT_MIME[fpath.suffix.lower()]
        b64 = base64.b64encode(fpath.read_bytes()).decode("ascii")
        return f"url('data:{mime};base64,{b64}')"

    out, n = FONT_URL_RE.subn(repl, html)
    print(f"{label}: inlined {n} font refs ({len(seen)} unique files)")
    # A dead `const CDN=".../cdn.shopify.com/..."` JS string + an unused
    # `p.img` field built from it linger in PORTFOLIO (superseded by the
    # `IMG[slug]` data:-URI lookup actually used for rendering) -- inert data,
    # never dereferenced, so it triggers no request. Only flag real load
    # vectors (src=/url()) as a decoupling regression.
    live_refs = re.findall(r'(?:src="https://cdn\.shopify\.com[^"]*"|url\([^)]*cdn\.shopify\.com[^)]*\))', out)
    print(f"{label}: live cdn.shopify.com load vectors -> {'FOUND ' + repr(live_refs[:3]) if live_refs else 'none'}")
    return out


def main():
    SITE.mkdir(parents=True, exist_ok=True)
    routes = {
        "comercial": MOCK / "gebeauty-b2b-portfolio-v6.html",
        "parceiros": MOCK / "gebeauty-portfolio-neutral-v1.html",
    }
    for route, src_path in routes.items():
        html = src_path.read_text(encoding="utf-8")
        html = inline_fonts(html, route)
        out_dir = SITE / route
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / "index.html"
        out_path.write_text(html, encoding="utf-8")
        print(f"wrote {out_path.relative_to(ROOT)} ({len(html)} bytes)\n")


if __name__ == "__main__":
    main()
